
networks:
  app_network:
    driver: bridge

services:
  bot:
    build: .
    container_name: bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    ports:
      - 8000:8000
    networks:
      - app_network
    volumes:
      - ./logs:/bot/logs

  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  pgdata:
