version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  bot:
    build: .
    container_name: bot
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
      - TOKEN=${TOKEN}
      - TZ=Europe/Moscow
    ports:
      - 8000:8000
    networks:
      - app_network
    volumes:
      - ./logs:/bot/logs